### ISSUE TITLE
Failed devtools::check()

### ISSUE THREAD

**Issue by jananiravi** [JRaviLab/MolEvolvR#105]
### Broached in https://github.com/JRaviLab/MolEvolvR/discussions/104

<div type='discussions-op-text'>

<sup>Originally posted by **Cateline** October 18, 2024</sup>
Hi team, @jananiravi @the-mayer @falquaddoomi @epbrenner 
I'm having issues running the devtools check for my code, which I believe is subsequently causing the pkgdown fail in my pull request. This is the error message I am getting. I'd really appreciate your help in resolving this issue
![image](https://github.com/user-attachments/assets/1559dacf-34f4-4f17-bdc6-ef54b8baa7b1)

</div>

**Comment by falquaddoomi** [comment]
As far as I can tell, this specific issue was due to the code in the `R` package in PR #103 including a call to `devtools::check()`. Since `devtools::check()`, includes loading the library, this executes the call to `devtools::check()` *within* the library, leading to an infinite regress.

Again AFAICT this is just an issue with PR #103, not the library, so I think this can be closed.
